CREATE TABLE `tbl_member_validator` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `uname` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `grade` INT(11) DEFAULT '0',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idx`),
  UNIQUE KEY `email_unique` (`email`),
  UNIQUE KEY `uid_unique` (`uid`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8