CREATE TABLE `tbl_board` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(10) DEFAULT NULL,
  `title` VARCHAR(30) DEFAULT NULL,
  `pwd` VARCHAR(100) CHARACTER SET latin1 NOT NULL,
  `contents` TEXT,
  `click` SMALLINT(6) NOT NULL DEFAULT '0',
  `ref` INT(11) DEFAULT NULL,
  `re_step` SMALLINT(6) DEFAULT NULL,
  `re_lvl` SMALLINT(6) DEFAULT NULL,
  `deleted` CHAR(1) CHARACTER SET latin1 DEFAULT NULL,
  `reg_ip` VARCHAR(20) CHARACTER SET latin1 NOT NULL,
  `mod_ip` VARCHAR(20) CHARACTER SET latin1 DEFAULT NULL,
  `reg_date` DATETIME NOT NULL,
  `mod_date` DATETIME DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=INNODB AUTO_INCREMENT=146 DEFAULT CHARSET=utf8